export class Urls {
  static user_list = '/user/list';

  static user_login = '/user/login';
  static resource_list = '/resource/list';
  static role_query = '/role/query';
  static user_exact_query = '/user/exact-query';
  static valid_session = '/user/valid-session';
  static role_list = '/role/list';
  static user_auth = '/user/authorize';
  static user_update = '/user/update';
  static user_add = '/user/add';
  static role_authorize = '/role/authorize';
  static role_add = '/role/save';
  static machine_list = '/machine/list';
  static username_valid = '/user/valid-name';
  static user_name_like_query = '/user/name-like-query';
  static merchant_name_like_query = '/merchant/name-like-query';
  static merchant_save = '/merchant/save';
  static machine_save = '/machine/save';
  static merchant_list = '/merchant/list';
  static goods_desc_list = '/goods-description/list';
  static goods_desc_add = '/goods-description/add';
  static goods_page = '/goods/page';
  static delivery_sheet_add = '/goods/add-delivery-sheet';
  static upload_machine_status = '/machine/upload-status';
  static order_page = '/order/page';
  static set_deliveryman = '/goods/set-deliveryman';
  static merchant_delete = '/merchant/delete';
  static get_sheet_page = '/goods/get-delivery-sheet-page';
}
